name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/aws-nodejs-mern .

      - name: Publish image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/aws-nodejs-mern:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/aws-nodejs-mern:latest

      - name: Stop and remove existing container
        run: |
          docker stop aws-nodejs-app-container || true
          docker rm aws-nodejs-app-container || true

      - name: Run Docker container
        run: |
          docker run -d -p 3010:3010 --name aws-nodejs-app-container \
            -e PORT="${{ secrets.PORT }}" \
            -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -e AWS_SECRET_KEY="${{ secrets.AWS_SECRET_KEY }}" \
            -e AWS_S3_BUCKET_NAME="${{ secrets.AWS_S3_BUCKET_NAME }}" \
            -e MONGO_URL="${{ secrets.MONGO_URL }}" \
            ${{ secrets.DOCKER_USERNAME }}/aws-nodejs-mern:latest

      - name: Verify container status
        run: docker ps -a | grep aws-nodejs-app-container
